import type { Review } from "./reviews-data";

export const fullReviews: Review[] = [
  {
    "id": "fr1",
    "username": "bright_seller",
    "avatar": "https://i.pravatar.cc/60?img=15",
    "flag": "https://flagcdn.com/24x18/gb.png",
    "timeAgo": "2 weeks ago",
    "rating": 5,
    "text": "Great service and clear guidance. Rasab Agency helped me set up my Shopify store from scratch and the results have been fantastic. The store looks professional and converts well. Will definitely hire again for future store builds and marketing campaigns.",
    "priceRange": "$180",
    "duration": "4 days",
    "serviceType": "Shopify Store Setup",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609505/IMG-20250921-WA0091_ymtuvy.jpg",
    "reply": "Thank you for the great review! Looking forward to working together again.",
    "showHelpful": false
  },
  {
    "id": "fr2",
    "username": "eco_stores",
    "avatar": "https://i.pravatar.cc/60?img=20",
    "flag": "https://flagcdn.com/24x18/de.png",
    "timeAgo": "3 weeks ago",
    "rating": 5,
    "text": "Delivered great results, communication was top-notch. The store looks and converts better now. Rasab Agency provided detailed analytics setup and helped optimize our product pages for better SEO performance. Highly professional work!",
    "priceRange": "$320",
    "duration": "6 days",
    "serviceType": "Store Optimization",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609405/IMG-20250921-WA0043_pdhfii.jpg",
    "showHelpful": true
  },
  {
    "id": "fr3",
    "username": "north_star",
    "avatar": "https://i.pravatar.cc/60?img=47",
    "flag": "https://flagcdn.com/24x18/ca.png",
    "timeAgo": "1 month ago",
    "rating": 5,
    "text": "Reliable, clear and fast. Delivered everything as promised with screen recordings and documentation. The Facebook Ads campaign setup was perfect and started generating leads immediately. Excellent value for money!",
    "priceRange": "$150",
    "duration": "3 days",
    "serviceType": "Facebook Ads Setup",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609506/IMG-20250921-WA0092_ieopxm.jpg",
    "reply": "Thanks for the feedback! Happy to help with your marketing success.",
    "showHelpful": false
  },
  {
    "id": "fr4",
    "username": "aussie_entrepreneur",
    "avatar": "https://i.pravatar.cc/60?img=25",
    "flag": "https://flagcdn.com/24x18/au.png",
    "timeAgo": "1 month ago",
    "rating": 5,
    "text": "Outstanding work on my dropshipping store! Rasab Agency set up everything perfectly - from product research to supplier integration. The store design is clean and professional. Sales started coming in within the first week. Couldn't be happier with the results!",
    "priceRange": "$450",
    "duration": "7 days",
    "serviceType": "Dropshipping Store",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609504/IMG-20250921-WA0090_g6lmty.jpg",
    "showHelpful": true
  },
  {
    "id": "fr5",
    "username": "tokyo_fashion",
    "avatar": "https://i.pravatar.cc/60?img=33",
    "flag": "https://flagcdn.com/24x18/jp.png",
    "timeAgo": "2 months ago",
    "rating": 5,
    "text": "Rasab Agency helped me launch my fashion brand online with a beautiful Shopify store. The design perfectly captures our brand aesthetic and the checkout process is smooth. He also set up our email marketing automation which has been generating great results. Highly recommended!",
    "priceRange": "$380",
    "duration": "5 days",
    "serviceType": "Fashion Store Build",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609405/IMG-20250921-WA0043_pdhfii.jpg",
    "reply": "Thank you! Your fashion brand has great potential. Wishing you continued success!",
    "showHelpful": false
  },
  {
    "id": "fr6",
    "username": "nordic_wellness",
    "avatar": "https://i.pravatar.cc/60?img=40",
    "flag": "https://flagcdn.com/24x18/se.png",
    "timeAgo": "2 months ago",
    "rating": 5,
    "text": "Exceptional service! Rasab Agency built our wellness product store and integrated it with our existing systems seamlessly. The Google Ads campaigns he set up have been consistently profitable. His attention to detail and follow-up support is outstanding.",
    "priceRange": "$290",
    "duration": "6 days",
    "serviceType": "Wellness Store + Ads",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609506/IMG-20250921-WA0092_ieopxm.jpg",
    "showHelpful": true
  },
  {
    "id": "fr7",
    "username": "spanish_artisan",
    "avatar": "https://i.pravatar.cc/60?img=8",
    "flag": "https://flagcdn.com/24x18/es.png",
    "timeAgo": "3 months ago",
    "rating": 5,
    "text": "Rasab Agency created a stunning online store for my handmade ceramics business. The product photography integration and inventory management system work flawlessly. International shipping setup was seamless and customer support features are excellent.",
    "priceRange": "$340",
    "duration": "8 days",
    "serviceType": "Artisan Store Build",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
    "reply": "Your ceramics are beautiful! Happy to help showcase your artistry online.",
    "showHelpful": false
  },
  {
    "id": "fr8",
    "username": "south_african_gems",
    "avatar": "https://i.pravatar.cc/60?img=12",
    "flag": "https://flagcdn.com/24x18/za.png",
    "timeAgo": "3 months ago",
    "rating": 5,
    "text": "Perfect execution on our jewelry store! The product zoom functionality and secure payment integration give customers confidence. The Meta Ads campaigns Rasab Agency set up have been driving consistent high-quality traffic and sales.",
    "priceRange": "$420",
    "duration": "9 days",
    "serviceType": "Jewelry Store + Ads",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
    "showHelpful": true
  },
  {
    "id": "fr9",
    "username": "finnish_tech",
    "avatar": "https://i.pravatar.cc/60?img=30",
    "flag": "https://flagcdn.com/24x18/fi.png",
    "timeAgo": "4 months ago",
    "rating": 5,
    "text": "Rasab Agency delivered an exceptional B2B e-commerce solution for our tech company. The custom integrations with our ERP system work perfectly and the admin dashboard is intuitive. The Google Ads strategy has generated quality leads consistently.",
    "priceRange": "$750",
    "duration": "12 days",
    "serviceType": "B2B E-commerce Solution",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
    "reply": "Thank you for trusting me with your complex project. Great working with your team!",
    "showHelpful": false
  },
  {
    "id": "fr10",
    "username": "belgian_chocolates",
    "avatar": "https://i.pravatar.cc/60?img=38",
    "flag": "https://flagcdn.com/24x18/be.png",
    "timeAgo": "4 months ago",
    "rating": 5,
    "text": "Outstanding work on our premium chocolate store! The subscription system integration and temperature-controlled shipping options work flawlessly. The store design perfectly reflects our luxury brand and conversions have exceeded expectations.",
    "priceRange": "$480",
    "duration": "10 days",
    "serviceType": "Premium Food Store",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
    "showHelpful": true
  },
  {
    "id": "add1",
    "username": "danish_design",
    "avatar": "https://i.pravatar.cc/60?img=16",
    "flag": "https://flagcdn.com/24x18/dk.png",
    "country": "Denmark",
    "timeAgo": "5 months ago",
    "rating": 5,
    "text": "Rasab Agency created a minimalist furniture store that perfectly represents our Scandinavian design philosophy. The user experience is clean and intuitive, and the inventory management system handles our complex product variations seamlessly.",
    "priceRange": "$520",
    "duration": "11 days",
    "serviceType": "Furniture Store Build",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609402/IMG-20250921-WA0039_htnlsc.jpg",
    "reply": "Thank you! Your furniture designs are truly inspiring. Happy to help bring them online!",
    "showHelpful": false
  },
  {
    "id": "add2",
    "username": "irish_organic",
    "avatar": "https://i.pravatar.cc/60?img=24",
    "flag": "https://flagcdn.com/24x18/ie.png",
    "country": "Ireland",
    "timeAgo": "5 months ago",
    "rating": 5,
    "text": "Exceptional work on our organic food marketplace! The multi-vendor system works perfectly and the subscription box feature has been a huge hit with customers. The SEO optimization has improved our visibility significantly.",
    "priceRange": "$680",
    "duration": "14 days",
    "serviceType": "Multi-vendor Marketplace",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
    "showHelpful": true
  },
  {
    "id": "add3",
    "username": "greek_pottery",
    "avatar": "https://i.pravatar.cc/60?img=41",
    "flag": "https://flagcdn.com/24x18/gr.png",
    "country": "Greece",
    "timeAgo": "6 months ago",
    "rating": 5,
    "text": "Rasab Agency built a beautiful store for our traditional Greek pottery. The cultural storytelling elements and product customization features work wonderfully. International shipping integration has opened up new markets for us.",
    "priceRange": "$360",
    "duration": "9 days",
    "serviceType": "Cultural Artisan Store",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
    "reply": "Your pottery is absolutely beautiful! Honored to help share Greek culture with the world.",
    "showHelpful": false
  },
  {
    "id": "add4",
    "username": "polish_amber",
    "avatar": "https://i.pravatar.cc/60?img=19",
    "flag": "https://flagcdn.com/24x18/pl.png",
    "country": "Poland",
    "timeAgo": "6 months ago",
    "rating": 5,
    "text": "Outstanding execution on our amber jewelry store! The product authentication system and certificate generation feature give customers confidence in our genuine Baltic amber. The store design is elegant and professional.",
    "priceRange": "$440",
    "duration": "10 days",
    "serviceType": "Jewelry Authentication Store",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
    "showHelpful": true
  },
  {
    "id": "add5",
    "username": "czech_crystal",
    "avatar": "https://i.pravatar.cc/60?img=27",
    "flag": "https://flagcdn.com/24x18/cz.png",
    "country": "Czech Republic",
    "timeAgo": "7 months ago",
    "rating": 5,
    "text": "Rasab Agency delivered an exceptional crystal and glassware store with stunning product galleries and 360-degree view functionality. The B2B wholesale section has streamlined our dealer relationships significantly.",
    "priceRange": "$590",
    "duration": "12 days",
    "serviceType": "Crystal Gallery + B2B Portal",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
    "reply": "Your crystal work is absolutely stunning! Thank you for the opportunity to showcase such artistry.",
    "showHelpful": false
  },
  {
    "id": "add6",
    "username": "hungarian_wine",
    "avatar": "https://i.pravatar.cc/60?img=36",
    "flag": "https://flagcdn.com/24x18/hu.png",
    "country": "Hungary",
    "timeAgo": "7 months ago",
    "rating": 5,
    "text": "Perfect wine e-commerce solution! The vintage tracking system, cellar management features, and age verification process work flawlessly. The tasting notes integration and wine pairing suggestions have enhanced customer experience.",
    "priceRange": "$650",
    "duration": "13 days",
    "serviceType": "Wine E-commerce + Features",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609402/IMG-20250921-WA0039_htnlsc.jpg",
    "showHelpful": true
  },
  {
    "id": "add7",
    "username": "portuguese_tiles",
    "avatar": "https://i.pravatar.cc/60?img=43",
    "flag": "https://flagcdn.com/24x18/pt.png",
    "country": "Portugal",
    "timeAgo": "8 months ago",
    "rating": 5,
    "text": "Rasab Agency created a magnificent store for our traditional Portuguese tiles (azulejos). The pattern visualization tool and custom design service integration have revolutionized how customers interact with our products.",
    "priceRange": "$480",
    "duration": "11 days",
    "serviceType": "Tile Design Studio",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
    "reply": "Your azulejos are works of art! Happy to help preserve and share this beautiful Portuguese tradition.",
    "showHelpful": false
  },
  {
    "id": "add8",
    "username": "austrian_alpine",
    "avatar": "https://i.pravatar.cc/60?img=14",
    "flag": "https://flagcdn.com/24x18/at.png",
    "country": "Austria",
    "timeAgo": "8 months ago",
    "rating": 5,
    "text": "Exceptional alpine sports equipment store! The gear compatibility checker and mountain weather integration provide incredible value to our customers. The seasonal inventory management system handles our complex product cycles perfectly.",
    "priceRange": "$720",
    "duration": "15 days",
    "serviceType": "Alpine Sports Store + Weather API",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
    "showHelpful": true
  },
  {
    "id": "add9",
    "username": "slovenian_honey",
    "avatar": "https://i.pravatar.cc/60?img=48",
    "flag": "https://flagcdn.com/24x18/si.png",
    "country": "Slovenia",
    "timeAgo": "9 months ago",
    "rating": 5,
    "text": "Beautiful organic honey store with educational content about beekeeping and sustainability. The subscription service for regular honey deliveries and the bee adoption program integration have created a loyal customer community.",
    "priceRange": "$380",
    "duration": "8 days",
    "serviceType": "Organic Honey Store + Subscriptions",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
    "reply": "Your commitment to sustainable beekeeping is inspiring! Happy to help spread awareness about bee conservation.",
    "showHelpful": false
  },
  {
    "id": "add10",
    "username": "estonian_digital",
    "avatar": "https://i.pravatar.cc/60?img=21",
    "flag": "https://flagcdn.com/24x18/ee.png",
    "country": "Estonia",
    "timeAgo": "9 months ago",
    "rating": 5,
    "text": "Cutting-edge digital services marketplace with blockchain integration for secure transactions. The smart contract system for service delivery and the reputation scoring algorithm work flawlessly. Truly innovative solution!",
    "priceRange": "$850",
    "duration": "18 days",
    "serviceType": "Blockchain Marketplace",
    "gigImage": "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
    "reply": "Your vision for blockchain integration was ahead of its time! Exciting to work on such innovative projects.",
    "showHelpful": false
  }
];
